### ISSUE TITLE
SalmonTE example doesn't work

### ISSUE THREAD

**Issue by sulevk** [hyunhwan-jeong/SalmonTE#69] opened 2022-06-19 04:44 UTC
Thank you for the salmonTE, great tool. However, running it is a bit cumbersome. After installation I tried to run example and got this:
./SalmonTE.py quant --reference=hs example
2022-06-19 12:39:55,355 Starting quantification mode
2022-06-19 12:39:55,356 Collecting FASTQ files...
2022-06-19 12:39:55,356 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2022-06-19 12:39:55,361 The input dataset is considered as a paired-ends dataset.
2022-06-19 12:39:55,362 Collected 4 FASTQ files.
2022-06-19 12:39:55,362 Quantification has been finished.
2022-06-19 12:39:55,362 Running Salmon using Snakemake
Traceback (most recent call last):
  File "/Users/sulevkoks/Terminalis/SalmonTE/./SalmonTE.py", line 292, in <module>
    run(args)
  File "/Users/sulevkoks/Terminalis/SalmonTE/./SalmonTE.py", line 243, in run
    run_salmon(param)
  File "/Users/sulevkoks/Terminalis/SalmonTE/./SalmonTE.py", line 143, in run_salmon
    snakemake.snakemake(
AttributeError: module 'snakemake' has no attribute 'snakemake'

It is MACOS 12.4. Thank you for your comments.

**Comment by hyunhwan-jeong** [comment] 2022-07-07 13:42
Duplicate of #70

**Closed** 2023-01-26 00:13 UTC
