### ISSUE TITLE
OSError: [Errno 8] Exec format error_ arm64_using a VM

### ISSUE THREAD

**Issue by lgallegovillar** [hyunhwan-jeong/SalmonTE#60] opened 2021-09-20 16:11 UTC
Hello Hyun-Hwan Jeong, 

I am trying to run SalmonTE on arm64 system (M1 Apple using a VM) and I get the following Errors:  

base) parallels@ubuntu-linux-20-04-desktop:~/SalmonTE$ python3 SalmonTE.py quant --reference=hs example
2021-09-20 18:04:21,274 Starting quantification mode
2021-09-20 18:04:21,274 Collecting FASTQ files...
2021-09-20 18:04:21,274 SalmonTE assumes that 'example' is a directory, and SalmonTE will search any FASTQ file in the directory.
2021-09-20 18:04:21,280 The input dataset is considered as a paired-ends dataset.
2021-09-20 18:04:21,280 Collected 4 FASTQ files.
2021-09-20 18:04:21,280 Quantification has been finished.
2021-09-20 18:04:21,280 Running Salmon using Snakemake
2021-09-20 18:04:21,394 Lock 281472830404064 acquired on /tmp/tmpfdzpcto1snakemake-runtime-source-cache/83e66b0398248c995f7650fca9486c37bf9ac41f5b80c89cfa9ab2f138cf3479.lock
2021-09-20 18:04:21,394 Lock 281472830404064 released on /tmp/tmpfdzpcto1snakemake-runtime-source-cache/83e66b0398248c995f7650fca9486c37bf9ac41f5b80c89cfa9ab2f138cf3479.lock
/home/parallels/SalmonTE/snakemake/Snakefile.paired:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

2021-09-20 18:04:21,420 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              4              1              1
total                      7              1              1

Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/home/parallels/.local/lib/python3.8/site-packages/snakemake/workflow.py", line 1060, in execute
    success = self.scheduler.schedule()
  File "/home/parallels/.local/lib/python3.8/site-packages/snakemake/scheduler.py", line 492, in schedule
    run = self.job_selector(needrun)
  File "/home/parallels/.local/lib/python3.8/site-packages/snakemake/scheduler.py", line 764, in job_selector_ilp
    self._solve_ilp(prob)
  File "/home/parallels/.local/lib/python3.8/site-packages/snakemake/scheduler.py", line 813, in _solve_ilp
    prob.solve(solver)
  File "/home/parallels/.local/lib/python3.8/site-packages/pulp/pulp.py", line 1880, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/parallels/.local/lib/python3.8/site-packages/pulp/apis/coin_api.py", line 134, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/home/parallels/.local/lib/python3.8/site-packages/pulp/apis/coin_api.py", line 193, in solve_CBC
    cbc = subprocess.Popen(args, stdout=pipe, stderr=pipe, stdin=devnull)
  File "/home/parallels/miniconda3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/parallels/miniconda3/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/parallels/.local/lib/python3.8/site-packages/pulp/apis/../solverdir/cbc/linux/64/cbc'
Traceback (most recent call last):
  File "SalmonTE.py", line 292, in <module>
    run(args)
  File "SalmonTE.py", line 243, in run
    run_salmon(param)
  File "SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/parallels/SalmonTE/SalmonTE_output/EXPR.csv'

Hope you can help me with this. 
Thanks, 
Lorena

**Comment by hyunhwan-jeong** [comment] 2021-09-24 14:10
Duplicate of #57, I will figure it out soon.

**Closed by hyunhwan-jeong** 2021-09-24 14:10 UTC
